### ISSUE TITLE
用在我的笔记里已经失效了，按ctrl+p获得是光标向上一行

### ISSUE THREAD

**Issue by stelvetica** [joodo/logseq-plugin-pin#1]

**Comment by joodo** [comment]
什么系统？linux 吗

**Comment by stelvetica** [comment]
windows，用quicker解决了 https://getquicker.net/Sharedaction?code=80b03c6d-8176-42f4-f913-08dd0fae75f2

**Comment by joodo** [comment]
或者你改一下快捷键试试，可以在设置里改
